---
- name: install essential repos (7)
  get_url: url=https://copr.fedoraproject.org/coprs/librehat/shadowsocks/repo/epel-7/librehat-shadowsocks-epel-7.repo
           dest=/etc/yum.repos.d/
  when: ansible_distribution_version >= '7'
  tags: prepare

- name: install essential repos (6)
  get_url: url=https://copr.fedoraproject.org/coprs/librehat/shadowsocks/repo/epel-6/librehat-shadowsocks-epel-6.repo
           dest=/etc/yum.repos.d/
  when: ansible_distribution_version < '7'
  tags: prepare

- name: install dependencies
  yum: name={{ item }}
  with_items: "{{ shadowsocks_dependencies }}"
  notify: restart shadowsocks-libev
  tags: install

- name: assure shadowsocks-libev home dir exists
  file: path={{ shadowsocks_home }} state=directory

- name: generate config file
  template: src=shadowsocks-libev.json
            dest={{ shadowsocks_home }}/shadowsocks-libev.json
            mode=640
            owner=root
            group=root
            force=yes
  notify: restart shadowsocks-libev
  tags: config

- name: sync init service (7)
  template: src=shadowsocks-libev.service
            dest=/usr/lib/systemd/system/
            mode=755
  when: ansible_distribution_version >= '7'
  tags: config

- name: sync init script (6)
  template: src=shadowsocks-libev.init
            dest=/etc/init.d/shadowsocks-libev
            mode=755
  when: ansible_distribution_version < '7'
  tags: config

- name: sync firewalld service
  template: src=shadowsocks-libev.firewalld
            dest=/etc/firewalld/services/shadowsocks-libev.xml
  when: ansible_distribution_version >= '7'
  register: shadowsocks_libev_firewalld_service_updated
  tags:
    - config
    - firewalld

- name: update firewalld service
  shell: firewall-cmd --reload
  when: ansible_distribution_version >= '7' and shadowsocks_libev_firewalld_service_updated.changed
  tags:
    - config
    - firewalld

- name: add shadowsocks-libev service for firewalld
  firewalld: zone=public
             service=shadowsocks-libev
             immediate=true
             permanent=true
             state=enabled
  when: ansible_distribution_version >= '7'
  tags:
    - config
    - firewalld

- name: tweak sysctl
  sysctl: name="{{ item.key }}"
          value="{{ item.value }}"
          state=present
          reload=yes
          ignoreerrors=yes
  with_items: "{{ shadowsocks_sysctl_params }}"
  when: shadowsocks_sysctl_tweak
  tags: sysctl

- name: enable tcp_fastopen if available
  sysctl: name=net.ipv4.tcp_fastopen
          value=3
          state=present
          reload=yes
  when: shadowsocks_fast_open and shadowsocks_sysctl_tweak and ansible_kernel | version_compare('3.7', '>=')
  tags: sysctl

- name: start and enable service
  service: name=shadowsocks-libev
           state=started
           enabled=yes
