---
- name: include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"
   - "main.yml"

# Setup/install tasks.
- include: RedHat.yml
  when: ansible_os_family == 'RedHat'
